backend:
  name: git-gateway
  repo: lsu-ddem/video-game-design
  branch: master # Branch to update (optional; defaults to master)
  accept_roles: 
    - admin 
    - editor 

media_folder: "/static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  # homepage 
  - name: "homepage" 
    label: "homepage" 
    folder: "content" 
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Order", name: "weight", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}

  # Unit 1 - Video Game Design Concepts
  - name: "Video Game Design Concepts" 
    label: "Video Game Design Concepts" 
    folder: "content/1_Concepts" 
    create: true 
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Order", name: "weight", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}

#   # Intro to Godot    
#   - name: "Intro to Godot" 
#     label: "Intro to Godot" 
#     folder: "content/1_IntroToCoding/1_CodingBasics" 
#     create: true 
#     fields: 
#       - {label: "Title", name: "title", widget: "string"}
#       - {label: "Order", name: "weight", widget: "number"}
#       - {label: "Body", name: "body", widget: "markdown"}    

#   # Lessons 
#   - name: "Getting Started" 
#     label: "Getting Started" 
#     folder: "content/1_IntroToCoding/1_CodingBasics/1_Lesson_1" 
#     create: true 
#     fields: 
#       - {label: "Title", name: "title", widget: "string"}
#       - {label: "Order", name: "weight", widget: "number"}
#       - {label: "Body", name: "body", widget: "markdown"}
#   - name: "Storing things in code" 
#     label: "Storing things in code" 
#     folder: "content/1_IntroToCoding/1_CodingBasics/2_Lesson_2" 
#     create: true 
#     fields: 
#       - {label: "Title", name: "title", widget: "string"}
#       - {label: "Order", name: "weight", widget: "number"}
#       - {label: "Body", name: "body", widget: "markdown"}
#   - name: "Everything is a number" 
#     label: "Everything is a number" 
#     folder: "content/1_IntroToCoding/1_CodingBasics/3_Lesson_3" 
#     create: true 
#     fields: 
#       - {label: "Title", name: "title", widget: "string"}
#       - {label: "Order", name: "weight", widget: "number"}
#       - {label: "Body", name: "body", widget: "markdown"}
 
# # Making Things Happen    
#   - name: "making Things Happen" 
#     label: "making Things Happen" 
#     folder: "content/1_IntroToCoding/2_MakingThings_Happen" 
#     create: true 
#     fields: 
#       - {label: "Title", name: "title", widget: "string"}
#       - {label: "Order", name: "weight", widget: "number"}
#       - {label: "Body", name: "body", widget: "markdown"}    

#   # Lessons 
#   - name: "Computers Making Choices" 
#     label: "Computers Making Choices" 
#     folder: "content/1_IntroToCoding/2_MakingThings_Happen/1_Lesson_1" 
#     create: true 
#     fields: 
#       - {label: "Title", name: "title", widget: "string"}
#       - {label: "Order", name: "weight", widget: "number"}
#       - {label: "Body", name: "body", widget: "markdown"}
#   - name: "Making Groups and Lists" 
#     label: "Making Groups and Lists" 
#     folder: "content/1_IntroToCoding/2_MakingThings_Happen/2_Lesson_2" 
#     create: true 
#     fields: 
#       - {label: "Title", name: "title", widget: "string"}
#       - {label: "Order", name: "weight", widget: "number"}
#       - {label: "Body", name: "body", widget: "markdown"}
#   - name: "Do it again" 
#     label: "Do it again" 
#     folder: "content/1_IntroToCoding/2_MakingThings_Happen/3_Lesson_3" 
#     create: true 
#     fields: 
#       - {label: "Title", name: "title", widget: "string"}
#       - {label: "Order", name: "weight", widget: "number"}
#       - {label: "Body", name: "body", widget: "markdown"}

# # Reuse it with modular code   
#   - name: "Reuse it with modular code" 
#     label: "Reuse it with modular code" 
#     folder: "content/1_IntroToCoding/3_ReuseItWithModularCode" 
#     create: true 
#     fields: 
#       - {label: "Title", name: "title", widget: "string"}
#       - {label: "Order", name: "weight", widget: "number"}
#       - {label: "Body", name: "body", widget: "markdown"}    

#   # Lessons 
#   - name: "Code that does a thing" 
#     label: "Code that does a thing" 
#     folder: "content/1_IntroToCoding/3_ReuseItWithModularCode/1_Lesson_1" 
#     create: true 
#     fields: 
#       - {label: "Title", name: "title", widget: "string"}
#       - {label: "Order", name: "weight", widget: "number"}
#       - {label: "Body", name: "body", widget: "markdown"}
#   - name: "Code that is a thing" 
#     label: "Code that is a thing" 
#     folder: "content/1_IntroToCoding/3_ReuseItWithModularCode/2_Lesson_2" 
#     create: true 
#     fields: 
#       - {label: "Title", name: "title", widget: "string"}
#       - {label: "Order", name: "weight", widget: "number"}
#       - {label: "Body", name: "body", widget: "markdown"}

  # Unit 2 - Intro to Godot 
  - name: "Intro to Godots" 
    label: "Intro to Godot" 
    folder: "content/2_Godot" 
    create: true 
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Order", name: "weight", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}


  # Unit 3 - Your First Game Basket Catch  
  - name: "Your First Game Basket Catch" 
    label: "Your First Game Basket Catch" 
    folder: "content/3_BasketCatch" 
    create: true 
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Order", name: "weight", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}
 

# Unit 4 - Your Second Game Asteroids   
  - name: "Your Second Game Asteroids" 
    label: "Your Second Game Asteroids" 
    folder: "content/4_Asteroids" 
    create: true 
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Order", name: "weight", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}
 

# Unit 5 - Game Design Microgames  
  - name: "Game Design Microgames" 
    label: "Game Design Microgames" 
    folder: "content/5_Microgames" 
    create: true 
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Order", name: "weight", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}
 
 # Unit 6 - Final Project 
  - name: "Final Project" 
    label: "Final Project" 
    folder: "content/5_FinalProject" 
    create: true 
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Order", name: "weight", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}
  